#!/usr/bin/env bash
# CSE server multitool
#
# This is a bundle of small utilities for using CSE servers and the
# infrastructure for assignments and other tasks.
#
# This is like the git command in that its actions are accessible via `cs
# <command>`. Most of these also require the environment variables `$COURSE`
# (e.g. `2041`) and `$TASK` (e.g. `lab03`).
#
# - `cs help` shows a summary of the available commands.
# - `cs fetch` to fetch the files for the task (like `1521 fetch lab03`) into
#   the current directory.
# - `cs task <task>` downloads the resources into a folder, but doesn't require
#   `$TASK` to be set.
# - `cs remote <cmd>...` to sync the files to CSE and run a command.
# - `cs autotest <test>...` to run an autotest on your files (like `2041
#   autotest shell_backup`)
# - `cs give <exercise> <files>...` to submit files for a given exercise. The
#   task is prepended to exercise, i.e. making `cs give shell_backup backup.sh`
#   run `give cs2041 lab05_shell_backup backup.sh`.
#
# These also assume that `rsync` is installed on your local sysm and that `ssh
# cse` connects to the CSE servers.

set -euo pipefail

cmd=$(basename "$0")

helpmsg() {
	cat << EOF
Usage: $cmd COMMAND [ARGS]...

General commands:
    help      Display this message and exit
    task      Set up a given task environment (requires \$COURSE)
    remote    Run a command on the CSE servers

Working on a given task (requires \$COURSE and \$TASK)
    fetch     Download provided material
    autotest  Run specified autotests
    give      Submit work
EOF
	exit
}

die() {
	echo "$cmd: $*"
	exit 1
}

require-env() {
	for arg in "$@"; do
		if [ -z "${!arg-}" ]; then
			die "$arg not set"
		fi
	done
}

cse() {
	ssh -t cse cd __workdir__ \; "$@"
}

fetch() {
	ssh -t cse rm -rf __workdir__ \; mkdir -p __workdir__

	cse "$COURSE" fetch "$TASK"

	scp -r cse:'__workdir__/*' .
}

autotest() {
	rsync --delete -avh . cse:__workdir__

	# -t to get colour output
	ssh -t -o LogLevel=QUIET cse cd __workdir__ \; "$COURSE" autotest "$@"
}

give() {
	if echo "$1" | grep -q '\.'; then
		subtask=${1%.*}
		echo "$(basename "$0"): give: deducing task as '$subtask'"
		give "$subtask" "$@"
		return
	fi

	rsync --delete -avh "${@:2}" cse:__workdir__
	yes yes | cse give "cs$COURSE" "${TASK}_$1" "${@:2}"
}

remote() {
	echo "Running on cse: $*"
	rsync --delete -a . cse:__workdir__
	cse "$@"
}

task() {
	# TODO handle insufficient args
	[ -n "${TASK-}" ] && die "task already set"
	[ -e "$1" ] && die "./$1 already exists"

	export TASK=$1

	mkdir "$TASK"
	cd "$TASK"
	echo "TASK=$TASK" > .env
	fetch
	echo "TASK=$TASK" > .env
}

main() {
	command="${1-}"
	shift || true

	case "$command" in
		fetch|autotest|give)
			require-env COURSE TASK
			"$command" "$@"
			;;
		task)
			require-env COURSE
			"$command" "$@"
			;;
		remote)
			"$command" "$@"
			;;
		""|help)
			helpmsg
			;;
		*)
			echo "$cmd: unknown command '$command'"
			;;
	esac
}

main "$@"
