#!/usr/bin/env bash
# Transparently run on the mounted filesystem
#
# This is a command wrapper that runs the command over ssh if you're in sshfs,
# and locally if you're on a local filesystem.
#
# You can also symlink other executables to this script, and `tunnel-run` will
# transparently tunnel them, or call the underlying executable if running
# locally. Doing this with svn or git, for example, can make those run
# reasonably fast.
#
# Warning: The commands will run on a completely different filesystem, so
# absolute paths passed to/from the tunnelled command will likely not be
# correct!
#
# Note that this does not detect what options were supplied to sshfs.
#
# Tip: you can ssh into the target machine with `tunnel-run sh -c 'exec $SHELL
# --login'`.

set -euo pipefail

# Detect if we're being run through a symlink
name=$(basename "$0")
truename=$(basename "$(realpath "$0")")

ssh-run() {
	local rel mountspec server basepath
	rel=$(realpath . --relative-to="$(df . --output=target | sed -n 2p)")

	mountspec=$(df . --output=source | sed -n 2p)
	server=$(cut -d: -f1 <<< "$mountspec")
	basepath=$(cut -d: -f2- <<< "$mountspec")

	basepath=${basepath:-.} # Empty = relative to "current" dir
	basepath=${basepath%/} # Strip trailing slash
	basepath=${basepath:-/} # ...but restore it if the basepath is the root folder

	# log "Running on $server relative to $basepath rel=$rel"

	extra_flags=""
	if [ -t 1 ]; then
		extra_flags="-qt"
	fi

	exec ssh $extra_flags -- "$server" "cd $(printf %q "$basepath/$rel") && exec $(printf "%q " "$@")"
}

local-run() {
	local cmd=$1
	shift

	realpath_self=$(realpath "$0")

	# We want to find the first command that *isn't* symlinked to us
	alt_bin=""
	while read -r candidate; do
		if [[ "$(realpath "$candidate")" != "$realpath_self" ]]; then
			alt_bin="$candidate"
			break
		fi
	done < <(which -a -- "$cmd" 2>/dev/null || true)

	if [ -n "$alt_bin" ]; then
		# Can't exec inside the loop since stdin won't be connected to the terminal
		# i.e. test -t 0 fails
		exec "$alt_bin" "$@"
	else
		PATH=":" exec "$cmd" "$@"
		exit "$?"
	fi
}

dispatch() {
	local fs
	# TODO(2022-06-25) this (and above) used $(realpath .) instead of just ., does that do anything?
	fs=$(df . --output=fstype | sed -n 2p)

	if [[ "${1:-}" = "locally" ]]; then
		fs=""
		shift
	fi

	if [[ "$#" = 0 ]]; then
		echo "Usage: $truename [locally] COMMAND [ARGS...]"
		exit
	fi

	case "$fs" in
		fuse.sshfs)
			ssh-run "$@"
			;;
		*)
			local-run "$@"
			;;
	esac
}

if [[ -L "$0" ]] && [[ "$name" != "$truename" ]]; then
	dispatch "$name" "$@"
else
	dispatch "$@"
fi
