#!/usr/bin/env python3
# Perform a JSON-RPC request on a websocket

import logging
import websockets
import click
import asyncio
import yaml
import json
import paramiko
import socket
from pathlib import Path
from urllib.parse import urlparse

log = logging.getLogger(__name__)

async_as_blocking = lambda fn: lambda *args, **kwargs: asyncio.run(fn(*args, **kwargs))
bind = lambda **ikwargs: lambda fn: lambda *args, **kwargs: fn(*args, **kwargs, **ikwargs)

def open_ssh_socket(hostname, port):
    # ssh config
    config = paramiko.config.SSHConfig.from_path(Path.home() / ".ssh/config")
    params = config.lookup(hostname)

    kwargs = {
        "hostname": params["hostname"],
        "look_for_keys": True,
    }

    if params.get("proxycommand", "none") != "none":
        kwargs["sock"] = paramiko.ProxyCommand(params["proxycommand"])

    if "port" in params:
        kwargs["port"] = int(params["port"])

    if "identityfile" in params:
        kwargs["key_filename"] = params["identityfile"]

    if "user" in params:
        kwargs["username"] = params["user"]

    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(**kwargs)

    tcpip = client.get_transport().open_channel("direct-tcpip", dest_addr=("127.0.0.1", port), src_addr=("127.0.0.1", port))
    sock = socket.fromfd(tcpip.fileno(), socket.AF_INET, socket.SOCK_STREAM)
    return sock

async def ws_rpc(method, params, kwargs):
    async with websockets.connect(**kwargs) as ws:
        await ws.send(json.dumps({
            "jsonrpc": "2.0",
            "id": 1,
            "method": method,
            "params": params,
        }))

        async for msg in ws:
            print(msg)
            msg = json.loads(msg)
            if not isinstance(msg, list):
                msg = [msg]

            for msg in msg:
                if "error" in msg:
                    log.warning("%s", msg["error"])
                if "result" in msg:
                    log.info("%s", msg["result"])
                if "params" in msg:
                    log.info("%s", msg["params"])

@click.command()
@click.argument("uri", type=str)
@click.argument("method", type=str)
@click.argument("params", type=str, nargs=-1)
@click.option("--ssh/--no-ssh", type=bool)
@async_as_blocking
async def cli(uri: str, method: str, params: list[str], ssh: bool):
    logging.basicConfig(
        format="%(asctime)s.%(msecs)03d [%(levelname)s] [%(name)s:%(lineno)d] %(message)s",
        datefmt="%Y%m%d:%H:%M:%S",
        level=logging.INFO,
    )

    params = [yaml.safe_load(p) for p in params]

    kwargs = {
        "uri": uri,
    }

    if ssh:
        parsed = urlparse(uri)
        kwargs["sock"] = open_ssh_socket(parsed.hostname, parsed.port)

    await ws_rpc(method, params, kwargs)

if __name__ == "__main__":
    cli()
